---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: test.yml
  hosts: all
  ansible_yum_repo: "https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:
